name: Oregon Small Satellite
description: Oregon Small Satellite Consortium
url: http://oresat.org

exclude:    ['README.markdown', 'LICENSE', 'CNAME', 'Makefile', 'assets/vendor/bootstrap', 'assets/less']
timezone:   America/Los_Angeles
markdown:   kramdown
permalink:  /:year/:month/:title/
excerpt_separator: "\n\n\n\n"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
